import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// This file is generated by FlutterFire CLI. Run 'flutterfire configure' to generate it.
import 'firebase_options.dart';
import 'src/features/auth/login_page.dart';
import 'src/features/auth/register_page.dart';
import 'src/features/auth/main_navigation.dart';
import 'src/common/widgets/auth_gate.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Firebase not configured yet - app will still run but auth won't work
    debugPrint('Firebase initialization failed: $e');
    debugPrint('Run "flutterfire configure" to set up Firebase');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Voice to Text',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginPage(),
        '/register': (context) => const RegisterPage(),
        '/home': (context) => const AuthGate(child: MainNavigation()),
        '/voice': (context) => const AuthGate(child: MainNavigation()),
        '/profile': (context) => const AuthGate(child: MainNavigation()),
      },
      onGenerateRoute: (settings) {
        // Route guarding for protected routes
        if (settings.name == '/voice' || settings.name == '/profile') {
          return MaterialPageRoute(
            builder: (context) => const AuthGate(child: MainNavigation()),
            settings: settings,
          );
        }
        return null;
      },
    );
  }
}
