import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// This file is generated by FlutterFire CLI. Run 'flutterfire configure' to generate it.
import 'firebase_options.dart';
import 'src/common/theme/app_theme.dart';
import 'src/common/routes/elevenlabs_page_route.dart';
import 'src/features/auth/login_page.dart';
import 'src/features/auth/register_page.dart';
import 'src/features/auth/main_navigation.dart';
import 'src/common/widgets/auth_gate.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    // Firebase not configured yet - app will still run but auth won't work
    debugPrint('Firebase initialization failed: $e');
    debugPrint('Run "flutterfire configure" to set up Firebase');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Voice to Text',
      theme: AppTheme.darkTheme,
      debugShowCheckedModeBanner: false,
      initialRoute: '/login',
      onGenerateRoute: (settings) {
        Widget page;
        switch (settings.name) {
          case '/login':
            page = const LoginPage();
            break;
          case '/register':
            page = const RegisterPage();
            break;
          case '/home':
          case '/voice':
          case '/profile':
            page = const AuthGate(child: MainNavigation());
            break;
          default:
            page = const LoginPage();
        }

        return ElevenLabsPageRoute(page: page, settings: settings);
      },
    );
  }
}
